stages:
  - build
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/woocommerce-moneybird-bol/${CI_COMMIT_TAG}/woocommerce-moneybird-bol.zip"

build_package:
  image: registry.gitlab.com/extensiontree/releaser:latest
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - "cd /builds/extensiontree/woocommerce-moneybird-bol; ./build.sh"
  artifacts:
    paths:
      - woocommerce-moneybird-bol.zip

upload_package:
  stage: upload
  image: curlimages/curl:latest
  needs: ['build_package']
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file woocommerce-moneybird-bol.zip "${PACKAGE_REGISTRY_URL}"

release_package:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  needs: ['upload_package']
  script:
    - echo 'running release job'
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: $CI_COMMIT_TAG
    description: './CHANGELOG.md'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Plugin zip package'
          filepath: '/package'
          url: '${PACKAGE_REGISTRY_URL}'
          link_type: 'package'